version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: javac C:\Java_Project\Test.java
workflows:
  my-workflow:
    jobs:
      - build
